# Generated by Django 6.0.6 on 2026-06-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tournament Title')),
                ('tournament_type', models.CharField(choices=[('SOLO', 'Solo (48 Players)'), ('DUO', 'Duo (24 Teams)'), ('SQUAD', 'Squad (12 Teams)')], default='SOLO', max_length=10, verbose_name='Match Type')),
                ('total_players', models.IntegerField(default=48, verbose_name='Total Players (e.g., 48 for Solo)')),
                ('entry_fee', models.IntegerField(verbose_name='Entry Fee (Per Player)')),
                ('prize_pool', models.IntegerField(verbose_name='Total Prize Pool')),
                ('per_kill', models.IntegerField(default=0, verbose_name='Per Kill Prize')),
                ('time_and_date', models.CharField(max_length=100, verbose_name='Match Time and Date')),
            ],
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
