# Generated by Django 6.0.6 on 2026-06-08 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_delete_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='entry_fee',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='per_kill',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='prize_pool',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='time_and_date',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='total_players',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='tournament_type',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='TournamentJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('freefire_uid', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('payment_ss', models.FileField(upload_to='payments/')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
    ]
