# Generated by Django 6.0.6 on 2026-06-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_remove_tournament_entry_fee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentjoin',
            name='payment_ss',
        ),
        migrations.AddField(
            model_name='tournamentjoin',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamentjoin',
            name='payment_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
