# Generated by Django 6.0.6 on 2026-06-09 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_remove_tournamentjoin_payment_ss_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentjoin',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='tournamentjoin',
            name='phone_number',
            field=models.CharField(help_text='BKash/Nagad Number', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamentjoin',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournament.tournament'),
        ),
    ]
